### ISSUE TITLE
PiStop with Python 3 on RPi 2

### ISSUE THREAD

**Issue by MrBarnes** [PiHw/Pi-Stop#2]
I've been trying out my PiStop using Python 3 on a raspberry Pi 2.
The code all seems to work, lights changing in sequence, however setting up the GPIO seems to call up some errors and I can't ind any documentation for using PiStop with Python, only for Scratch.

I've tried using GPIO.setwarnings(False) to hide the errors but it hasn't made any difference.

Here are the errors I am receiving.

Warning (from warnings module):
  File "/home/pi/Documents/Pi-Stop-Test.py", line 4
    GPIO.setup (3, GPIO.OUT)
RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.

Warning (from warnings module):
  File "/home/pi/Documents/Pi-Stop-Test.py", line 4
    GPIO.setup (3, GPIO.OUT)
RuntimeWarning: A physical pull up resistor is fitted on this channel!

Warning (from warnings module):
  File "/home/pi/Documents/Pi-Stop-Test.py", line 5
    GPIO.setup (5, GPIO.OUT)
RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.

Warning (from warnings module):
  File "/home/pi/Documents/Pi-Stop-Test.py", line 5
    GPIO.setup (5, GPIO.OUT)
RuntimeWarning: A physical pull up resistor is fitted on this channel!

Warning (from warnings module):
  File "/home/pi/Documents/Pi-Stop-Test.py", line 6
    GPIO.setup (7, GPIO.OUT)
RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.

**Comment by meltwater2000** [comment]
Hi. Thanks for using the PiStop.

There is currently the following example available:
https://github.com/PiHw/Pi-Stop/blob/master/non_markdown/pytonpriateworkshop/code-commented/lighthouse.py

But I've not yet produced a Python workshop, due to time commitments. Although I will be creating some at some point.

The "Pull-Up warnings" are new to the RPi.GPIO library, I tested and get the same on mine too.  These pins are shared with the I2C driver (so if you have that enabled it may detect they are considered "in use").  The pins do have physical pull-ups on them, as this is used for I2C devices, but this only has an impact if you are using them as inputs and trying to set internal pull-downs (although you will notice that by default these pins will light the PiStop LEDs).
The "channel already in use warning"...ensure you call GPIO.cleanup() at the end of your script (I usually put it in a finally part of a try which runs the main code - so breaking using keyboard will still run it) which will release these pins.

Good news is that these warnings should have no impact on running the code (although the setwarnings "should" remove them-but may be a bug).

**Comment by MrBarnes** [comment]
Thanks. I've managed to remove all but 2 of the errors by moving the code to hide errors.

An example of how you are running the clean up would be great.

We are busy setting up a scheme of work using  and hiding the GPIO in a different file so that the pupils only see functions. Which is what I'm trying to do with yours too but not sure how to make sure pupils cleanup correctly without restarting.

Have you considered an extra board with a single push button switch to allow pupils to extend work further?

Rick Barnes
Head of Computing
Sent from my hudl

On 18 Feb 2015 23:07, meltwater2000 <notifications@github.com> wrote:

Hi. Thanks for using the PiStop.

There is currently the following example available:
https://github.com/PiHw/Pi-Stop/blob/master/non_markdown/pytonpriateworkshop/code-commented/lighthouse.py

But I've not yet produced a Python workshop, due to time commitments. Although I will be creating some at some point.

The "Pull-Up warnings" are new to the RPi.GPIO library, I tested and get the same on mine too. These pins are shared with the I2C driver (so if you have that enabled it may detect they are considered "in use"). The pins do have physical pull-ups on them, as this is used for I2C devices, but this only has an impact if you are using them as inputs and trying to set internal pull-downs (although you will notice that by default these pins will light the PiStop LEDs).
The "channel already in use warning"...ensure you call GPIO.cleanup() at the end of your script (I usually put it in a finally part of a try which runs the main code - so breaking using keyboard will still run it) which will release these pins.

Good news is that these warnings should have no impact on running the code (although the setwarnings "should" remove them-but may be a bug).

-

**Comment by meltwater2000** [comment]
Probably the best way is to make the PiStop into a class, then you can add the setup and the clean up in the constructor and destructor.  I'll see if I have time to create a quick example to add to the GitHub over the weekend for you.

For my more general scripts I usually call the main() from a try/finally condition, so if you have an error or ctrl+z the code, it will always clean up.


```
. . . define other functions at top. . .

def main():
  GPIOsetup()
  while True:
    TrafficGo()
    time.sleep(5)
    TrafficStop()
    time.sleep(5)    

try:
  main()
finally:
  print ("Finish")
  GPIO.cleanup()
```

Yes have a few ideas in development...lots more workshops, new hardware and other surprises, as and when there is time.

**Comment by MrBarnes** [comment]
Thanks. That looks great I'll have a play tonight.

I've not used OO yet hoping to find time for some tutorials at work.

Rick.

On Feb 20, 2015 9:06 AM, meltwater2000 <notifications@github.com> wrote:

Probably the best way is to make the PiStop into a class, then you can add the setup and the clean up in the constructor and destructor. I'll see if I have time to create a quick example to add to the GitHub over the weekend for you.

For my more general scripts I usually call the main() from a try/finally condition, so if you have an error or ctrl+z the code, it will always clean up.

. . . define other functions at top. . .

def main():
  GPIOsetup()
  while True:
    TrafficGo()
    time.sleep(5)
    TrafficStop()
    time.sleep(5)

try:
  main()
finally:
  print ("Finish")
  GPIO.cleanup()


Yes have a few ideas in development...lots more workshops, new hardware and other surprises, as and when there is time.

**Comment by meltwater2000** [comment]
I've added an example for the PiStop using a class, let me know if you have any issues (a fairly quick test with it).
https://github.com/PiHw/Pi-Stop/blob/master/python_source/pistop.py

I'll add some additional comments later to explain it better.

NOTE:
RPi.GPIO v0.5.10 has issues with GPIO pins above 26 on RPi2, but version RPi.GPIO v0.5.11 is fine.

**Comment by meltwater2000** [comment]
Rick,
I've tweaked the class a little bit (pins were around the wrong way!).  I've also provided a traffic light example on how to use it.  Let me know how you get on.

**Comment by meltwater2000** [comment]
Module released which supports python3.
Issue closed.
